# dependabot.yml configuration for keeping dependencies up to date
# Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily" # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions):"
      include: "scope"
